# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Build steps
script:
  - make

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
    - libboost1.55-all-dev

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
	    - boost-latest	    	    
          packages:
            - g++-4.9
	    - libboost1.55-all-dev
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
	    - boost-latest	    
          packages:
            - g++-5
	    - libboost1.55-all-dev	    
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
	    - boost-latest	    	    
          packages:
            - clang-3.6
	    - libboost1.55-all-dev	    
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
	    - boost-latest	    	    
          packages:
            - clang-3.7
	    - libboost1.55-all-dev	    	    
      env: COMPILER=clang++-3.7