# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

install:
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"

# Build steps
script:
  - cd build
  - cmake ..
  - make
  - make test

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-5
    - g++-5
    - libboost1.55-all-dev
    - cmake